# Generated by Django 6.1.1 on 2026-09-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_genre'),
        ('catalog', '0006_remove_book_id_book_book_id_shelfbook_added_at_and_more'),
    ]

    operations = [
    ]
