# Generated by Django 6.1.1 on 2026-10-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_readinglog_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinggoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='readinglog',
            options={},
        ),
    ]
